eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: med.elaalouch@gmail.com
    password: gekj acsy kcyg gjlj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
